### ISSUE TITLE
Add PRNG seeding for reproducible data generation in testing environment

### ISSUE THREAD

**Issue by cavokz** [elastic/elastic-integration-corpus-generator-tool#21]
During unit testing it's necessary to generate data in a producible way. To do so it should be possible to seed the PRNG before the generation step.

**Comment by endorama** [comment]
Hi @cavokz, just to double check I understood the use case here: are you referring to this tool tests (`_test.go` files in this repo) or are you referring to the capability of producing the same output data to be used in external systems?

I'm assuming you are referring to the second case here. From my understanding this should already happen due to how seeding works in Golang. Without explicitly calling [`rand.Seed()`](https://pkg.go.dev/math/rand#Seed) it behaves like with `rand.Seed(1)`. (see also https://go.dev/play/p/xZNnm-YMp6I)

The current code is not updating the seed, so `math/rand` is already using the same seed.

I tested if data generation was reproducible and it seems this is not the case, and from my understanding this is due to internal implementation not due to the random seed. @aspacca maybe you can chime in with more details.

**Comment by aspacca** [comment]
> I tested if data generation was reproducible and it seems this is not the case, and from my understanding this is due to internal implementation not due to the random seed.

it is because for a few types we use `github.com/Pallinder/go-randomdata`: unless specifically overridden the default seed for this package is based on current timestamp https://github.com/Pallinder/go-randomdata/blob/master/random_data.go#L92

we could call [`randomdata.CustomRand(rand.New(rand.NewSource(1)))`](https://github.com/Pallinder/go-randomdata/blob/master/random_data.go#L102-L104)

**Comment by cavokz** [comment]
> Hi @cavokz, just to double check I understood the use case here: are you referring to this tool tests (`_test.go` files in this repo) or are you referring to the capability of producing the same output data to be used in external systems?

Yes, I was just referring to the `_test.go` files. Frankly I don't remember the exact need of this issue, probably it was just a kind of reminder after a call with @aspacca.

**Comment by aspacca** [comment]
now that we have #98 and #97 we can print them in the tests so in case of failure we can seed the same in order to reproduce.
we still want to have some fuzziness in the tests and not set a fixed seed and timeNow so that on the long run we might be able to catch corner case
